//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ribichenko_kurs
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int Id_product { get; set; }
        public string Name { get; set; }
        public string Article { get; set; }
        public string Unit { get; set; }
        public string Price { get; set; }
        public string Much { get; set; }
    }
}
