//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ribichenko_kurs
{
    using System;
    using System.Collections.Generic;
    
    public partial class Record
    {
        public int Id_record { get; set; }
        public string Name { get; set; }
        public string Login { get; set; }
        public string Much { get; set; }
        public int Id_user { get; set; }
    
        public virtual User User { get; set; }
    }
}
